### ISSUE TITLE
Rounded bar charts

### ISSUE THREAD

**Issue by bcolas** [webdetails/ccc#404]
Is there a way to round bar charts ?

![image](https://github.com/webdetails/ccc/assets/8590669/2b4625ff-464f-4601-8963-dc185b29fcc9)

**Comment by dcleao** [comment]
This is not offered out of the box. It should be possible to achieve using some advanced protovis, but overall very hard to properly support all features, such as selection and borders. Here's an example of a chart that uses a `pv.Wedge` protovis mark to add a half-circle on top of a panel: https://jsfiddle.net/duarteleao/GWyNH/. However, this technique would not allow to properly show borders around the composite shape.

**Comment by bcolas** [comment]
Many thanks for your answer. 
I will look at this !
